services:
  admin-panel:
    image: ghcr.io/glam3k/simple-stoat-admin:latest
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - stoat
    ports:
      - 127.0.0.1:3100:3000

networks:
  stoat:
    external: true
